const players = [
  {
    id: 1,
    name: "Leo Messi",
    pays: "Argentine",
    club: "Inter Miami",
    post: "attaquant",
    age: 37,
    note: undefined,
    attributs_Physiques: {
      agilite: 10,
      endurance: 10,
      force: 10,
      vitesse: 10,
    },
    attributs_Techniques: {
      controle_de_balle: 10,
      dribble: 10,
      passes: 10,
      tir: 10,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    pays: "Portugal",
    club: "Al Nassr",
    post: "attaquant",
    age: 39,
    note: undefined,
    attributs_Physiques: {
      agilite: 9,
      endurance: 9,
      force: 10,
      vitesse: 9,
    },
    attributs_Techniques: {
      controle_de_balle: 9,
      dribble: 8,
      passes: 8,
      tir: 10,
    },
  },
  {
    id: 3,
    name: "Neymar Jr",
    pays: "Brésil",
    club: "Al Hilal",
    post: "attaquant",
    age: 32,
    note: undefined,
    attributs_Physiques: {
      agilite: 10,
      endurance: 8,
      force: 7,
      vitesse: 9,
    },
    attributs_Techniques: {
      controle_de_balle: 10,
      dribble: 10,
      passes: 9,
      tir: 9,
    },
  },
  {
    id: 4,
    name: "Kylian Mbappé",
    pays: "France",
    club: "Paris Saint-Germain",
    post: "attaquant",
    age: 25,
    note: undefined,
    attributs_Physiques: {
      agilite: 9,
      endurance: 9,
      force: 8,
      vitesse: 10,
    },
    attributs_Techniques: {
      controle_de_balle: 9,
      dribble: 9,
      passes: 8,
      tir: 9,
    },
  },
  {
    id: 5,
    name: "Robert Lewandowski",
    pays: "Pologne",
    club: "FC Barcelone",
    post: "attaquant",
    age: 35,
    note: undefined,
    attributs_Physiques: {
      agilite: 8,
      endurance: 9,
      force: 9,
      vitesse: 7,
    },
    attributs_Techniques: {
      controle_de_balle: 8,
      dribble: 7,
      passes: 8,
      tir: 10,
    },
  },
  {
    id: 6,
    name: "Kevin De Bruyne",
    pays: "Belgique",
    club: "Manchester City",
    post: "milieu",
    age: 33,
    note: undefined,
    attributs_Physiques: {
      agilite: 8,
      endurance: 9,
      force: 8,
      vitesse: 7,
    },
    attributs_Techniques: {
      controle_de_balle: 9,
      dribble: 8,
      passes: 10,
      tir: 8,
    },
  },
  {
    id: 7,
    name: "Mohamed Salah",
    pays: "Égypte",
    club: "Liverpool",
    post: "attaquant",
    age: 32,
    note: undefined,
    attributs_Physiques: {
      agilite: 9,
      endurance: 9,
      force: 7,
      vitesse: 9,
    },
    attributs_Techniques: {
      controle_de_balle: 8,
      dribble: 9,
      passes: 7,
      tir: 9,
    },
  },
  {
    id: 8,
    name: "Virgil van Dijk",
    pays: "Pays-Bas",
    club: "Liverpool",
    post: "défenseur",
    age: 33,
    note: undefined,
    attributs_Physiques: {
      agilite: 7,
      endurance: 8,
      force: 10,
      vitesse: 7,
    },
    attributs_Techniques: {
      controle_de_balle: 7,
      dribble: 6,
      passes: 8,
      tir: 6,
    },
  },
  {
    id: 9,
    name: "Erling Haaland",
    pays: "Norvège",
    club: "Manchester City",
    post: "attaquant",
    age: 24,
    note: undefined,
    attributs_Physiques: {
      agilite: 8,
      endurance: 8,
      force: 10,
      vitesse: 9,
    },
    attributs_Techniques: {
      controle_de_balle: 8,
      dribble: 7,
      passes: 7,
      tir: 10,
    },
  },
  {
    id: 10,
    name: "Luka Modrić",
    pays: "Croatie",
    club: "Real Madrid",
    post: "milieu",
    age: 38,
    note: undefined,
    attributs_Physiques: {
      agilite: 9,
      endurance: 8,
      force: 7,
      vitesse: 7,
    },
    attributs_Techniques: {
      controle_de_balle: 10,
      dribble: 9,
      passes: 10,
      tir: 7,
    },
  },
  {
    id: 11,
    name: "Karim Benzema",
    pays: "France",
    club: "Al-Ittihad",
    post: "attaquant",
    age: 36,
    note: undefined,
    attributs_Physiques: {
      agilite: 8,
      endurance: 8,
      force: 8,
      vitesse: 7,
    },
    attributs_Techniques: {
      controle_de_balle: 9,
      dribble: 8,
      passes: 9,
      tir: 9,
    },
  },
];
module.exports = { players };
